### ISSUE TITLE
Support for entries?

### ISSUE THREAD

**Issue by karllhughes** [mariosant/feedbin-nodejs#1]
Maybe this library just isn't complete, but it doesn't look like it supports entries yet. Happy to help if you want a pr @mariosant!

**Comment by mariosant** [comment]
I am gladly accepting PRs @karllhughes! 
To be honest I asked for a dev account so I can test things but I never got one 😑

**Comment by karllhughes** [comment]
Oh nice. I don't think you actually need a developer account. I just signed up this morning and my account worked with the API right away.

I'll try to get you a PR for a couple of those methods later today. Thanks!
